# JVM & Memory Settings
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Code Style & AndroidX
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Performance & Build Optimizations
org.gradle.parallel=true
org.gradle.caching=true
android.dependency.excludeLibraryComponentsFromConstraints=true

# Disable AGP built-in Kotlin compiler to allow standard Kotlin Gradle plugin
android.builtInKotlin=false
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
