name: Build Debug APK on Release

on:
  release:
    types: [created, published]
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Get version name
        id: version
        run: echo "VERSION_NAME=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: DisplayLauncher-${{ steps.version.outputs.VERSION_NAME }}-debug.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30
